### ISSUE TITLE
StorableWrap is useless

### ISSUE THREAD

**Issue by vagarenko** [maurer/c-storable-deriving#3]
Am I missing something?
Isn't this instance:

```
instance (Storable a) => CStorable (StorableWrap a)
```

completly useless?
Why would I want CStorable if I already have Storable?
It should be other way round:

```
instance(Generic a, CStorable (Rep a)) => Storable (StorableWrap a)
```

so I could derive Generic instance for my type, wrap it with StorableWrap and feed it to some function that takes Storable.

**Comment by vagarenko** [comment]
Take a look at https://hackage.haskell.org/package/generic-storable

**Comment by maurer** [comment]
`StorableWrap` is meant for use with functions which consume something belonging to the typeclass `CStorable`, when people want a shortcut for using a `Storable` object instead.

e.g.

```
f :: (CStorable a) -> IO ()
f (StorableWrap somethingStorable)
```

If you want something the other way around as well, feel free to write it and submit a PR, but this codepath is not useless, it is actually in use.
