### ISSUE TITLE
Is CStorable really necessary?

### ISSUE THREAD

**Issue by ocharles** [maurer/c-storable-deriving#7]
Typically when providing these generic implementation packages, you provide top level functions that act as stubs for the actual type class your interested in. I would propose that this:

``` haskell
class CStorable a where
  cPeek              :: Ptr a -> IO a
  default cPeek      :: (Generic a, GCStorable (Rep a)) => Ptr a -> IO a
  cPeek p            = fmap to $ gcPeek 0 (castPtr p)

  cPoke              :: Ptr a -> a -> IO ()
  default cPoke      :: (Generic a, GCStorable (Rep a)) => Ptr a -> a -> IO ()
  cPoke p x          = gcPoke 0 (castPtr p) $ from x

  cAlignment         :: a -> Int
  default cAlignment :: (Generic a, GCStorable (Rep a)) => a -> Int
  cAlignment         = gcAlignment . from

  cSizeOf            :: a -> Int
  default cSizeOf    :: (Generic a, GCStorable (Rep a)) => a -> Int
  cSizeOf            = gcSizeOf 0 . from
```

Becomes just

``` haskell
gpeek      :: (Generic a, GCStorable (Rep a)) => Ptr a -> IO a
gpeek p            = fmap to $ gcPeek 0 (castPtr p)

gpoke      :: (Generic a, GCStorable (Rep a)) => Ptr a -> a -> IO ()
gpoke p x          = gcPoke 0 (castPtr p) $ from x

galignment :: (Generic a, GCStorable (Rep a)) => a -> Int
galignment         = gcAlignment . from

gsizeOf    :: (Generic a, GCStorable (Rep a)) => a -> Int
gsizeOf            = gcSizeOf 0 . from
```

Your users would then do

``` haskell
data Foo = Foo { a :: X, b :: Y }
  deriving (Generic)

instance Storable Foo where
  peek = gpeek
  poke = gpoke
  sizeOf = gsizeOf
  alignment = galignment
```

See https://hackage.haskell.org/package/generic-deriving-1.9.0/docs/Generics-Deriving-Monoid.html for a similar example (note they don't export a copy of the `Monoid` type class, but just the necessary implementations for the methods).

**Comment by maurer** [comment]
`CStorable` is intended to represent a separate concept from `Storable` - I even have one or two types with different implementations for each. `CStorable` is intended to represent the way to treat this struct specifically as a C-analog of itself. `Storable` simply implies there's a way to write it to a chunk of memory.
